### PR TITLE
Fix use-after-free of zfsvfs after unmount

### LINKED ISSUE #282: Repeatedly creating and destroying zpool causes BSOD
I'm working on a test that does mount/unmount of a file based pool, repeatedly running the tool consistently causes the system to crash with this dump:

```
25: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

SYSTEM_THREAD_EXCEPTION_NOT_HANDLED (7e)
This is a very common BugCheck.  Usually the exception address pinpoints
the driver/function that caused the problem.  Always note this address
as well as the link date of the driver/image that contains this address.
Arguments:
Arg1: ffffffffc0000005, The exception code that was not handled
Arg2: fffff80127e5cd78, The address that the exception occurred at
Arg3: fffff50472507788, Exception Record Address
Arg4: fffff50472506fc0, Context Record Address

Debugging Details:
------------------


KEY_VALUES_STRING: 1

    Key  : AV.Dereference
    Value: NullClassPtr

    Key  : AV.Fault
    Value: Read

    Key  : Analysis.CPU.mSec
    Value: 2858

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 37773

    Key  : Analysis.Init.CPU.mSec
    Value: 3999

    Key  : Analysis.Init.Elapsed.mSec
    Value: 38171

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 110

    Key  : WER.OS.Branch
    Value: vb_release

    Key  : WER.OS.Timestamp
    Value: 2019-12-06T14:06:00Z

    Key  : WER.OS.Version
    Value: 10.0.19041.1


FILE_IN_CAB:  MEMORY.DMP

BUGCHECK_CODE:  7e

BUGCHECK_P1: ffffffffc0000005

BUGCHECK_P2: fffff80127e5cd78

BUGCHECK_P3: fffff50472507788

BUGCHECK_P4: fffff50472506fc0

EXCEPTION_RECORD:  fffff50472507788 -- (.exr 0xfffff50472507788)
ExceptionAddress: fffff80127e5cd78 (nt!CcGetPartition+0x0000000000000008)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 00000000000000a8
Attempt to read from address 00000000000000a8

CONTEXT:  fffff50472506fc0 -- (.cxr 0xfffff50472506fc0)
rax=0000000000000000 rbx=0000000000000000 rcx=0000000000000000
rdx=7fffffffffffff01 rsi=0000000000000000 rdi=0000000000000000
rip=fffff80127e5cd78 rsp=fffff504725079c0 rbp=fffff50472507a70
 r8=fffff50472507aa0  r9=0000000000000001 r10=0000000000000000
r11=fffff504725078f0 r12=ffffffffffffff01 r13=ffff84013c892b00
r14=ffffffffffffffff r15=ffff8401c375b6a0
iopl=0         nv up ei ng nz na po nc
cs=0010  ss=0018  ds=002b  es=002b  fs=0053  gs=002b             efl=00050286
nt!CcGetPartition+0x8:
fffff801`27e5cd78 4883b9a800000000 cmp     qword ptr [rcx+0A8h],0 ds:002b:00000000`000000a8=????????????????
Resetting default scope

BLACKBOXBSD: 1 (!blackboxbsd)


BLACKBOXNTFS: 1 (!blackboxntfs)


BLACKBOXPNP: 1 (!blackboxpnp)


BLACKBOXWINLOGON: 1

PROCESS_NAME:  System

READ_ADDRESS:  00000000000000a8 

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  00000000000000a8

EXCEPTION_STR:  0xc0000005

STACK_TEXT:  
fffff504`725079c0 fffff801`27f44885     : 00000000`00000000 ffff8401`c375b7b0 00000000`00000000 ffff8401`c375b610 : nt!CcGetPartition+0x8
fffff504`72507a10 fffff801`27e57ce8     : 00000000`00000000 ffff8402`09185680 ffffffff`ffffffff ffff8401`3c892b00 : nt!CcGetFlushedValidData+0x55
fffff504`72507a90 fffff801`27e50545     : ffff8401`8257ce60 fffff801`27e57800 ffff8401`3c73bc01 ffff8402`00000000 : nt!CcWriteBehindInternal+0x438
fffff504`72507b70 fffff801`27f0e6f5     : ffff8401`7e952040 00000000`00000080 ffff8401`3c73c040 000f8067`bcbbbdff : nt!ExpWorkerThread+0x105
fffff504`72507c10 fffff801`280059a8     : ffff9e80`be71c180 ffff8401`7e952040 fffff801`27f0e6a0 00000000`00000001 : nt!PspSystemThreadStartup+0x55
fffff504`72507c60 00000000`00000000     : fffff504`72508000 fffff504`72502000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x28


SYMBOL_NAME:  nt!CcGetPartition+8

MODULE_NAME: nt

IMAGE_NAME:  ntkrnlmp.exe

STACK_COMMAND:  .cxr 0xfffff50472506fc0 ; kb

BUCKET_ID_FUNC_OFFSET:  8

FAILURE_BUCKET_ID:  AV_nt!CcGetPartition

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {810c593a-284a-44fa-272d-68b1f00e1211}

Followup:     MachineOwner
---------

```

### PR DESCRIPTION
**Pull request by EchterAgo**
During unmount `zfsvfs` is destroyed and the pointer is zeroed in the VCB. There is however still a copy of the pointer in the DCB.

Windows can still call into `zfs_AcquireForLazyWrite`, through `CcMgr` after unmount and this would use the already freed `zfsvfs` pointer.

To fix this we set the pointer to zero in the DCB and add a zero check in `zfs_AcquireForLazyWrite`, `zfs_AcquireForReadAhead` and `fastio_acquire_for_mod_write`.

fixes #282

### CODE REVIEW

**Comment by EchterAgo** [comment]
With this the tests.py with no delay finally passes consistently.

**Comment by EchterAgo** [comment]
Should we include removing the delays from the tests in this PR or in #286?

**Comment by EchterAgo** [comment]
This test can be used to easily reproduce the error:

```batch
fsutil file createnew C:\testfolder\poolfile.bin 200000000

:hans
C:\tools\zfs\zpool.exe create tank \\?\C:\testfolder\poolfile.bin
C:\tools\zfs\zpool.exe destroy tank
goto hans

del C:\testfolder\poolfile.bin
```

**Comment by andrewc12** [comment]
I think the test changes should be in this pr

**Comment by andrewc12** [comment]
I don't think it matters as long as they get merged with or after this one gets merged

**Comment by EchterAgo** [comment]
Yay, `test5_py` passed!

**Comment by EchterAgo** [comment]
Hmmm, I think there is an issue with this, `zfs_AcquireForLazyWrite` could still be called between freeing the VCB `zfsvfs` and setting it to zero in DCB. The mutex does not guard against this because it is *in* `zfsvfs`. Maybe we should set a flag in mount?

**Comment by EchterAgo** [comment]
We also can't just `vfs_setfsprivate(zmo_dcb, NULL);` before `zfs_vfs_unmount` because it could fail. It also looks like if `zfs_vfs_unmount` fails things are already in a bad state. We could check `zmo_dcb->vpb->Flags & VPB_MOUNTED` in `zfs_AcquireForLazyWrite`

**Comment by EchterAgo** [comment]
Updated to add `VPB_MOUNTED` check, I ran `tests.py` in a loop for a while and didn't see any problems.

**Comment by EchterAgo** [comment]
Sorry, converting to draft because I think my last change is wrong, checking the `VPB_MOUNTED` flag will likely prevent data from flushing.

**Comment by EchterAgo** [comment]
We should also have a test for flushing on unmount, I'll try to add one.

**Comment by EchterAgo** [comment]
Ideally we'd set both `zmo` and `zmo_dcb`s `fsprivate` to zero before freeing it, but at the same location, at the end of `zfs_vfs_unmount`. I'll push such a change soon.

**Comment by EchterAgo** [comment]
Updated, I think that is the best I can come up with :\

**Comment by EchterAgo** [comment]
After running multiple create/destroy scripts, there is still something wrong:

```
 kd> k
 # Child-SP          RetAddr               Call Site
00 ffffd086`dde6e128 fffff800`15517f82     nt!DbgBreakPointWithStatus
01 ffffd086`dde6e130 fffff800`15517566     nt!KiBugCheckDebugBreak+0x12
02 ffffd086`dde6e190 fffff800`153fd747     nt!KeBugCheck2+0x946
03 ffffd086`dde6e8a0 fffff800`1541ed73     nt!KeBugCheckEx+0x107
04 ffffd086`dde6e8e0 fffff800`21f1e6e8     nt!ObReferenceObjectByPointer+0x21bec3
05 ffffd086`dde6e920 fffff800`22220a3e     OpenZFS!vflush+0x168 [H:\dev\openzfs\module\os\windows\spl\spl-vnode.c @ 1604] 
06 ffffd086`dde6e9b0 fffff800`22268f1f     OpenZFS!zfs_vfs_unmount+0xce [H:\dev\openzfs\module\os\windows\zfs\zfs_vfsops.c @ 1609] 
07 ffffd086`dde6eb40 fffff800`2221c5d5     OpenZFS!zfs_windows_unmount+0x41f [H:\dev\openzfs\module\os\windows\zfs\zfs_vnops_windows_mount.c @ 1581] 
08 ffffd086`dde6f430 fffff800`21f23906     OpenZFS!zfs_ioc_unmount+0x55 [H:\dev\openzfs\module\os\windows\zfs\zfs_ioctl_os.c @ 916] 
09 ffffd086`dde6f470 fffff800`2221c405     OpenZFS!zfsdev_ioctl_common+0x816 [H:\dev\openzfs\module\zfs\zfs_ioctl.c @ 7866] 
0a ffffd086`dde6f550 fffff800`221ff13d     OpenZFS!zfsdev_ioctl+0x2c5 [H:\dev\openzfs\module\os\windows\zfs\zfs_ioctl_os.c @ 866] 
0b ffffd086`dde6f640 fffff800`221fea46     OpenZFS!ioctlDispatcher+0x32d [H:\dev\openzfs\module\os\windows\zfs\zfs_vnops_windows.c @ 6400] 
0c ffffd086`dde6f710 fffff800`15210665     OpenZFS!dispatcher+0x1e6 [H:\dev\openzfs\module\os\windows\zfs\zfs_vnops_windows.c @ 7312] 
0d ffffd086`dde6f800 fffff800`1560142c     nt!IofCallDriver+0x55
0e ffffd086`dde6f840 fffff800`15601081     nt!IopSynchronousServiceTail+0x34c
0f ffffd086`dde6f8e0 fffff800`156003f6     nt!IopXxxControlFile+0xc71
10 ffffd086`dde6fa20 fffff800`15410ef8     nt!NtDeviceIoControlFile+0x56
11 ffffd086`dde6fa90 00007fff`6666d0c4     nt!KiSystemServiceCopyEnd+0x28
12 00000085`de71cec8 00007fff`6413591b     ntdll!NtDeviceIoControlFile+0x14
13 00000085`de71ced0 00007fff`64645921     KERNELBASE!DeviceIoControl+0x6b
14 00000085`de71cf40 00007ff7`a5d895d7     KERNEL32!DeviceIoControlImplementation+0x81
15 00000085`de71cf90 00000000`00000000     zpool!zcmd_ioctl_compat+0xe7 [H:\dev\openzfs\lib\libzfs_core\os\windows\libzfs_core_ioctl.c @ 54] 
```

File: module/os/windows/zfs/zfs_vnops_windows.c [hunk 1]
```diff
@@ -132,6 +132,11 @@ zfs_AcquireForLazyWrite(void *Context, BOOLEAN Wait)
 	struct vnode *vp = fo->FsContext;
 	dprintf("%s:fo %p\n", __func__, fo);
 
+	if (unlikely(zfsvfs == NULL)) {
+		dprintf("%s: fo %p already freed zfsvfs\n", __func__, fo);
+		return (FALSE);
+	}
+
```
Comment (lundman) [inline module/os/windows/zfs/zfs_vnops_windows.c:139]: Looks good, but there are 3 nearly identical calls. AcquireLazyWrite, AcquireReadAhead and at the end, fastio_acquire_for_mod_write.

**Review by lundman — CHANGES_REQUESTED** [review]

**Comment by lundman** [comment]
> 04 ffffd086`dde6e8e0 fffff800`21f1e6e8     nt!ObReferenceObjectByPointer+0x21bec3
> 05 ffffd086`dde6e920 fffff800`22220a3e     OpenZFS!vflush+0x168 [H:\dev\openzfs\module\os\windows\spl\spl-vnode.c @ 1604] 
> 

This is unrelated, and has been a thorn for quite some time.

File: module/os/windows/zfs/zfs_vnops_windows.c [hunk 2]
```diff
@@ -7950,6 +7960,12 @@ fastio_acquire_for_mod_write(PFILE_OBJECT FileObject,
 	NTSTATUS Status = STATUS_INVALID_PARAMETER;
 	dprintf("%s: \n", __func__);
 
+	if (unlikely(zfsvfs == NULL)) {
+		dprintf("%s: fo %p already freed zfsvfs\n", __func__,
+			FileObject);
+		return (FALSE);
```
Comment (lundman) [inline module/os/windows/zfs/zfs_vnops_windows.c:7966]: return (STATUS_INVALID_PARAMETER);

**Comment by EchterAgo** [comment]
> This is unrelated, and has been a thorn for quite some time.

Yea, I found #95 which seems to be the same. I added my info there.

File: module/os/windows/zfs/zfs_vnops_windows.c (hunk 1 above)
Comment (EchterAgo) [reply module/os/windows/zfs/zfs_vnops_windows.c:139]: Updated

File: module/os/windows/zfs/zfs_vnops_windows.c (hunk 2 above)
Comment (EchterAgo) [reply module/os/windows/zfs/zfs_vnops_windows.c]: Fixed

**Review by lundman — APPROVED** [review]

**Comment by EchterAgo** [comment]
I think there are a bunch more locations that might need a NULL check, I have a change for that too, but haven't tested it enough yet.

Better to have a NULL dereference than having to chase a use-after-free though.

**Comment by lundman** [comment]
Generally, all requests to ZFS come in via `dispatcher()`. There are 3 exceptions, guess which ones they are :)

**Comment by lundman** [comment]
`./module/os/windows/zfs/zfs_vnops_windows.c: 7965: continuation should be indented 4 spaces`

**Comment by EchterAgo** [comment]
Fix for checkstyle
